version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.02
    environment:
      
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: 
          name: Build Docker Image
          command: |
            set +x
            export DOCKER_CLI_EXPERIMENTAL=enabled
            export DOCKER_BUILDKIT=1
            TAG=0.1.$CIRCLE_BUILD_NUM
            mkdir -p ~/.docker/cli-plugins/
            curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.7.0/buildx-v0.7.0.linux-amd64
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            update-binfmts --enable
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build --platform linux/arm/v7,linux/arm64/v8,linux/amd64
            docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t msroest/sabnzbd_exporter:latest .
            docker tag msroest/sabnzbd_exporter:latest msroest/sabnzbd_exporter:$TAG
            docker images
      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login -u $DOCKERLOGIN -p $DOCKERPASS
              docker push msroest/sabnzbd_exporter:0.1.$CIRCLE_BUILD_NUM
              docker push msroest/sabnzbd_exporter:latest
            fi
