version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: 17.11.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run: 
        name: Build Docker Image
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t msroest/sabnzbd_exporter:$TAG .
          docker images